### PR TITLE
Upgrade to mysqli for php7 and older versions

### PR DESCRIPTION
**Pull request by codepotato**
Hi there! 

Updated your code to work with the current versions of MySQL and PHP. 

This update drops the mysql_connect (now removed from PHP7, and deprecated in other versions) for mysqli_connect.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi @codepotato, sorry for taking a while to get back to you, it's awesome someone has swung by to do this thank you! I don't really work with PHP/WordPress  much anymore so I haven't needed it.

It looks like you might have your editor configured to adjust whitespace? The whitespace changes here make it absolutely impossible to tell what has changed 😞  do you know how to fixup a commit to remove that?

If not I can walk you though - it might be worth also adding a .editorconfig file here to prevent this happening again.

**Comment by codepotato** [comment]
Thanks, @ErisDS. I'll get this fixed and re-pushed.

**Comment by codepotato** [comment]
Hi @ErisDS, 
Just reverted back to the last commit you made, included an editorconfig file and made the same changes again 😄 

Is that any clearer? Essentially, everything that used mysql_ is now mysqli_. 

Thanks! :)

**Comment by codepotato** [comment]
And huge apologies for the tardy reply to your comment : clients :)

**Comment by codepotato** [comment]
@ErisDS Sorry to bug, but would you be able to pull this branch as this will bring the code up to PHP7 (current). 

Thanks! (still happy to take over the running of this repo if you want)

**Comment by ErisDS** [comment]
I just came across this. I genuinely thought I had given you access and replied.

Waaay to late now I imagine, but it is done. Open to anyone who wants to take this repo on.

**Pull request merged**
